export const BeatfilmMoviesApiUrl = 'https://api.nomoreparties.co/';

export const cards = [
  {
    "id":1,
    "isLiked": true,
    "nameRU":"«Роллинг Стоунз» в изгнании",
    "nameEN":"Stones in Exile",
    "director":"Стивен Кайак ",
    "country":"США",
    "year":"2010",
    "duration":61,
    "trailerLink":"https://www.youtube.com/watch?v=UXcqcdYABFw",
    "created_at":"2020-11-23T14:12:21.376Z",
    "updated_at":"2020-11-23T14:12:21.376Z",
    "image":{
      "id":1,
      "name":"stones-in-exile",
      "alternativeText":"",
      "caption":"",
      "width":512,
      "height":279,
      "formats":{
        "thumbnail":{
          "hash":"thumbnail_stones_in_exile_b2f1b8f4b7",
          "ext":".jpeg",
          "mime":"image/jpeg",
          "width":245,
          "height":134,
          "size":8.79,
          "path":null,
          "url":"/uploads/thumbnail_stones_in_exile_b2f1b8f4b7.jpeg"
        },
        "small":{
          "hash":"small_stones_in_exile_b2f1b8f4b7",
          "ext":".jpeg",
          "mime":"image/jpeg",
          "width":500,
          "height":272,
          "size":25.68,
          "path":null,
          "url":"/uploads/small_stones_in_exile_b2f1b8f4b7.jpeg"
        }
      },
      "hash":"stones_in_exile_b2f1b8f4b7",
      "ext":".jpeg",
      "mime":"image/jpeg",
      "size":25.53,
      "url":"/uploads/stones_in_exile_b2f1b8f4b7.jpeg",
      "provider":"local",
      "provider_metadata":null,
      "created_at":"2020-11-23T14:11:57.313Z",
      "updated_at":"2020-11-23T14:11:57.313Z"
    }
  },
  {
    "id":2,
    "nameRU":"All Tomorrow's Parties",
    "nameEN":"All Tomorrow's Parties",
    "director":" Джонатан Кауэтт",
    "country":"Великобритания",
    "year":"2009",
    "duration":82,
    "trailerLink":"https://www.youtube.com/watch?v=D5fBhbEJxEU",
    "created_at":"2020-11-23T14:15:19.238Z",
    "updated_at":"2020-11-23T14:15:19.238Z",
    "image":{
      "id":2,
      "name":"all-tommoros-parties",
      "alternativeText":"",
      "caption":"",
      "width":699,
      "height":266,
      "formats":{
        "thumbnail":{
          "hash":"thumbnail_all_tommoros_parties_33a125248d",
          "ext":".jpeg",
          "mime":"image/jpeg",
          "width":245,
          "height":93,
          "size":10.33,
          "path":null,
          "url":"/uploads/thumbnail_all_tommoros_parties_33a125248d.jpeg"
        },
        "small":{
          "hash":"small_all_tommoros_parties_33a125248d",
          "ext":".jpeg",
          "mime":"image/jpeg",
          "width":500,
          "height":190,
          "size":35.24,
          "path":null,
          "url":"/uploads/small_all_tommoros_parties_33a125248d.jpeg"
        }
      },
      "hash":"all_tommoros_parties_33a125248d",
      "ext":".jpeg",
      "mime":"image/jpeg",
      "size":67.06,
      "url":"/uploads/all_tommoros_parties_33a125248d.jpeg"
    }
  },
  {
    "id":3,
    "nameRU":" Без обратного пути",
    "nameEN":"No Distance Left to Run",
    "director":"Уилл Лавлейс, Дилан Сотерн",
    "country":"Великобритания",
    "year":"2010",
    "duration":104,
    "trailerLink":"https://www.youtube.com/watch?v=6iYxdghpJZY",
    "created_at":"2020-11-23T14:17:23.257Z",
    "updated_at":"2020-11-23T14:17:23.257Z",
    "image":{
      "id":3,
      "name":"blur",
      "alternativeText":"",
      "caption":"",
      "width":460,
      "height":298,
      "formats":{
        "thumbnail":{
          "hash":"thumbnail_blur_a43fcf463d",
          "ext":".jpeg",
          "mime":"image/jpeg",
          "width":241,
          "height":156,
          "size":8.32,
          "path":null,
          "url":"/uploads/thumbnail_blur_a43fcf463d.jpeg"
        }
      },
      "hash":"blur_a43fcf463d",
      "ext":".jpeg",
      "mime":"image/jpeg",
      "size":21.07,
      "url":"/uploads/blur_a43fcf463d.jpeg"
    }
  },
  {
    "id":4,
    "isLiked": true,
    "nameRU":"Bassweight",
    "nameEN":"Bassweight",
    "director":"Сурид Хассан",
    "country":"Великобритания",
    "year":"2008",
    "duration":61,
    "trailerLink":"https://www.youtube.com/watch?v=dgSyC6me-jQ",
    "created_at":"2020-12-02T16:48:01.794Z",
    "updated_at":"2020-12-02T16:48:01.794Z",
    "image":{
      "id":4,
      "name":"загруженное",
      "alternativeText":"",
      "caption":"",
      "width":276,
      "height":183,
      "formats":{
        "thumbnail":{
          "hash":"thumbnail_zagruzhennoe_113f557116",
          "ext":".jpeg",
          "mime":"image/jpeg",
          "width":235,
          "height":156,
          "size":6.59,
          "path":null,
          "url":"/uploads/thumbnail_zagruzhennoe_113f557116.jpeg"
        }
      },
      "hash":"zagruzhennoe_113f557116",
      "ext":".jpeg",
      "mime":"image/jpeg",
      "size":7.01,
      "url":"/uploads/zagruzhennoe_113f557116.jpeg"
    },
  },
  {
    "id":5,
    "nameRU":"Taqwacore: The Birth of Punk Islam",
    "nameEN":"Taqwacore: The Birth of Punk Islam",
    "director":" Омар Маджид",
    "country":"Канада",
    "year":"2009",
    "duration":80,
    "trailerLink":"https://www.youtube.com/watch?v=JMZ8DO9F4Mo",
    "created_at":"2020-12-02T20:35:14.745Z",
    "updated_at":"2020-12-02T20:35:14.745Z",
    "image":{
      "id":5,
      "name":"taqwacore2",
      "alternativeText":"",
      "caption":"",
      "width":730,
      "height":411,
      "formats":{
        "thumbnail":{
          "hash":"thumbnail_taqwacore2_2f487d2e74",
          "ext":".jpeg",
          "mime":"image/jpeg",
          "width":245,
          "height":138,
          "size":7.01,
          "path":null,
          "url":"/uploads/thumbnail_taqwacore2_2f487d2e74.jpeg"
        },
        "small":{
          "hash":"small_taqwacore2_2f487d2e74",
          "ext":".jpeg",
          "mime":"image/jpeg",
          "width":500,
          "height":282,
          "size":16.29,
          "path":null,
          "url":"/uploads/small_taqwacore2_2f487d2e74.jpeg"
        }
      },
      "hash":"taqwacore2_2f487d2e74",
      "ext":".jpeg",
      "mime":"image/jpeg",
      "size":24.89,
      "url":"/uploads/taqwacore2_2f487d2e74.jpeg"
    },
  },
  {
    "id":6,
    "nameRU":"Фавела на взрыве",
    "nameEN":"Favela on Blast",
    "director":"Уэсли Пенц",
    "country":"Бразилия",
    "year":"2008",
    "duration":80,
    "trailerLink":"https://www.youtube.com/watch?v=Cugdwa7mndA",
    "created_at":"2020-12-02T20:37:33.665Z",
    "updated_at":"2020-12-02T20:37:33.665Z",
    "image":{
      "id":6,
      "name":"881707734_640",
      "alternativeText":"",
      "caption":"",
      "width":640,
      "height":360,
      "formats":{
        "thumbnail":{
          "hash":"thumbnail_881707734_640_d6a3a43358",
          "ext":".jpeg",
          "mime":"image/jpeg",
          "width":245,
          "height":138,
          "size":6.09,
          "path":null,
          "url":"/uploads/thumbnail_881707734_640_d6a3a43358.jpeg"
        },
        "small":{
          "hash":"small_881707734_640_d6a3a43358",
          "ext":".jpeg",
          "mime":"image/jpeg",
          "width":500,
          "height":281,
          "size":17.26,
          "path":null,
          "url":"/uploads/small_881707734_640_d6a3a43358.jpeg"
        }
      },
      "hash":"881707734_640_d6a3a43358",
      "ext":".jpeg",
      "mime":"image/jpeg",
      "size":23.67,
      "url":"/uploads/881707734_640_d6a3a43358.jpeg"
    },
  },
  {
    "id":7,
    "nameRU":"Постеры, сошедшие со стен",
    "nameEN":"The Posters Came from the Walls",
    "director":"Джереми Деллер, Николас Абрахамс",
    "country":"Великобритания",
    "year":"2008",
    "duration":72,
    "trailerLink":"https://www.youtube.com/watch?v=VFMU3crg0sM",
    "created_at":"2020-12-02T20:40:08.342Z",
    "updated_at":"2020-12-02T20:40:08.342Z",
    "image":{
      "id":7,
      "name":"posters-came-from-the-walls-2009-001-posters",
      "alternativeText":"",
      "caption":"",
      "width":1000,
      "height":750,
      "formats":{
        "thumbnail":{
          "hash":"thumbnail_posters_came_from_the_walls_2009_001_posters_180fe1a19f",
          "ext":".jpeg",
          "mime":"image/jpeg",
          "width":208,
          "height":156,
          "size":10.53,
          "path":null,
          "url":"/uploads/thumbnail_posters_came_from_the_walls_2009_001_posters_180fe1a19f.jpeg"
        },
        "medium":{
          "hash":"medium_posters_came_from_the_walls_2009_001_posters_180fe1a19f",
          "ext":".jpeg",
          "mime":"image/jpeg",
          "width":750,
          "height":563,
          "size":92.16,
          "path":null,
          "url":"/uploads/medium_posters_came_from_the_walls_2009_001_posters_180fe1a19f.jpeg"
        },
        "small":{
          "hash":"small_posters_came_from_the_walls_2009_001_posters_180fe1a19f",
          "ext":".jpeg",
          "mime":"image/jpeg",
          "width":500,
          "height":375,
          "size":46.34,
          "path":null,
          "url":"/uploads/small_posters_came_from_the_walls_2009_001_posters_180fe1a19f.jpeg"
        }
      },
      "hash":"posters_came_from_the_walls_2009_001_posters_180fe1a19f",
      "ext":".jpeg",
      "mime":"image/jpeg",
      "size":153.63,
      "url":"/uploads/posters_came_from_the_walls_2009_001_posters_180fe1a19f.jpeg"
    },
  },
  {
    "id":8,
    "nameRU":"Soul Power",
    "nameEN":"Soul Power",
    "director":"Джеффри Леви-Хинте",
    "country":"США",
    "year":"2008",
    "duration":92,
    "trailerLink":"https://www.youtube.com/watch?v=8OprNgiOq-I",
    "created_at":"2020-12-02T20:57:31.683Z",
    "updated_at":"2020-12-02T20:57:31.683Z",
    "image":{
      "id":8,
      "name":"images",
      "alternativeText":"",
      "caption":"",
      "width":266,
      "height":189,
      "formats":{
        "thumbnail":{
          "hash":"thumbnail_images_5bfcbf36e6",
          "ext":".jpeg",
          "mime":"image/jpeg",
          "width":220,
          "height":156,
          "size":8.89,
          "path":null,
          "url":"/uploads/thumbnail_images_5bfcbf36e6.jpeg"
        }
      },
      "hash":"images_5bfcbf36e6",
      "ext":".jpeg",
      "mime":"image/jpeg",
      "size":10.06,
      "url":"/uploads/images_5bfcbf36e6.jpeg"
    },
  },
  {
    "id":9,
    "nameRU":" 196 ударов в минуту",
    "nameEN":"196 BPM",
    "director":"Ромуальд Кармакар",
    "country":"Германия",
    "year":"2003",
    "duration":60,
    "trailerLink":"https://www.youtube.com/watch?v=GsDRVpdgNJ4",
    "created_at":"2020-12-02T20:59:53.997Z",
    "updated_at":"2020-12-02T20:59:53.997Z",
    "image":{
      "id":9,
      "name":"загруженное (1)",
      "alternativeText":"",
      "caption":"",
      "width":560,
      "height":292,
      "formats":{
        "thumbnail":{
          "hash":"thumbnail_zagruzhennoe_1_fd5faff237",
          "ext":".jpeg",
          "mime":"image/jpeg",
          "width":245,
          "height":128,
          "size":5.57,
          "path":null,
          "url":"/uploads/thumbnail_zagruzhennoe_1_fd5faff237.jpeg"
        },
        "small":{
            "hash":"small_zagruzhennoe_1_fd5faff237",
            "ext":".jpeg",
            "mime":"image/jpeg",
            "width":500,
            "height":261,
            "size":17.87,
            "path":null,
            "url":"/uploads/small_zagruzhennoe_1_fd5faff237.jpeg"
          }
      },
      "hash":"zagruzhennoe_1_fd5faff237",
      "ext":".jpeg",
      "mime":"image/jpeg",
      "size":19.39,
      "url":"/uploads/zagruzhennoe_1_fd5faff237.jpeg"
    },
  },
  {
    "id":10,
    "nameRU":" Hit So Hard: Школа жизни Патти Шемель",
    "nameEN":"Hit So Hard: The Life & Near Death Story of Patty Schemel",
    "director":"П.Дэвид Эберсол",
    "country":"США",
    "year":"2011",
    "duration":103,
    "trailerLink":"https://www.youtube.com/watch?v=DMvFMeaGj_w",
    "created_at":"2020-12-02T21:02:28.791Z",
    "updated_at":"2020-12-02T21:02:28.791Z",
    "image":{
      "id":10,
      "name":"images",
      "alternativeText":"",
      "caption":"",
      "width":300,
      "height":168,
      "formats":{
        "thumbnail":{
          "hash":"thumbnail_images_244e1fd56f",
          "ext":".jpeg",
          "mime":"image/jpeg",
          "width":245,
          "height":137,
          "size":11.76,
          "path":null,
          "url":"/uploads/thumbnail_images_244e1fd56f.jpeg"
        }
      },
      "hash":"images_244e1fd56f",
      "ext":".jpeg",
      "mime":"image/jpeg",
      "size":14.8,
      "url":"/uploads/images_244e1fd56f.jpeg"
    },
  },
];
